spring.application.name=POS-MilleniumGames
server.port=8080
# CONEXIÓN A POSTGRESQL
# Asegúrate de crear la base de datos con este mismo nombre en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/pos_milleniumgames
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# CONFIGURACIÓN JPA / HIBERNATE
# 'update' crea o actualiza las tablas sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ZONA HORARIA Y FECHAS
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/El_Salvador
# SUBIDA DE ARCHIVOS (PORTADAS DE JUEGOS)
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB